sudo: false
language: objective-c
os: osx
osx_image: xcode10

matrix:
  include:
    - env: ACTION=test_ios12
    - env: ACTION=test_ios11
    - env: ACTION=test_tvos12
    - env: ACTION=test_tvos11
    - env: ACTION=test_ios_swift3
    - env: ACTION=test_ios_swift4
    - env: ACTION=test_tvos_swift3
    - env: ACTION=test_tvos_swift4
    - osx_image: xcode9.4
      env: ACTION=test_xcode9_ios_swift3
    - osx_image: xcode9.4
      env: ACTION=test_xcode9_ios_swift4
    - env: ACTION=pod_lint
    - env: ACTION=carthage_build

script:
  - instruments -s devices # List all available simulators
  - bundle exec fastlane $ACTION
