language: objective-c
sudo: false
osx_image: xcode9.1

matrix:
  include:
    - os: osx
      env: ACTION=test_ios11
    - os: osx
      env: ACTION=test_ios10
    - os: osx
      env: ACTION=test_tvos11
    - os: osx
      env: ACTION=test_tvos10
    - os: osx
      osx_image: xcode8.3
      env: ACTION=test_ios10_legacy
    - os: osx
      osx_image: xcode8.3
      env: ACTION=test_tvos10_legacy

script:
  - bundle exec fastlane $ACTION
