language: objective-c
sudo: false
osx_image: xcode9.3

matrix:
  include:
    - os: osx
      env: ACTION=test_ios11
    - os: osx
      env: ACTION=test_ios10
    - os: osx
      env: ACTION=test_tvos11
    - os: osx
      env: ACTION=test_tvos10
    - os: osx
      env: ACTION=test_ios_swift3
    - os: osx
      env: ACTION=test_tvos_swift3
    - os: osx
      env: ACTION=pod_lint
    - os: osx
      env: ACTION=carthage_build

script:
  - instruments -s devices # List all available simulators
  - bundle exec fastlane $ACTION
